name: tson
description: TSON, short for Typed JSON, is a binary-encoded serialization of JSON-like document that support javascript typed data and CStringList. A CStringList can efficiently store very large collection of strings, it internally stores its elements in a byte array.
version: 1.1.0
author: am <alexandre.maurel@gmail.com>
homepage: https://github.com/amaurel/TSON

environment:
  sdk: '>=1.0.0 <2.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
